{% set name = "hcloud" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hcloud-{{ version }}.tar.gz
  sha256: 31d2acb265bee425750a03ceaf52485849257423bace20d2dd9f4fff9250d9e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - future >=0.17.1,<1
    - python-dateutil >=2.7.5,<3
    - requests >=2.20,<3

test:
  imports:
    - hcloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hetznercloud/hcloud-python
  summary: hcloud-python is a library for the Hetzner Cloud API
  license: MIT
  license_file: LICENSE
  doc_url: https://hcloud-python.readthedocs.io
  dev_url: https://github.com/hetznercloud/hcloud-python

extra:
  recipe-maintainers:
    - s-m-e
