{% set name = "hcloud" %}
{% set version = "1.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hcloud-{{ version }}.tar.gz
  sha256: 845fa0a6d34b01e2eda591abc0e7b3c057a2843b75b260a9e1090ae6510d307a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - future >=0.17.1,<1
    - python-dateutil >=2.7.5,<3
    - requests >=2.20,<3

test:
  imports:
    - hcloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hetznercloud/hcloud-python
  summary: hcloud-python is a library for the Hetzner Cloud API
  license: MIT
  license_file: LICENSE
  doc_url: https://hcloud-python.readthedocs.io
  dev_url: https://github.com/hetznercloud/hcloud-python

extra:
  recipe-maintainers:
    - s-m-e
